### ISSUE TITLE
Not working on Sketch 3.4

### ISSUE THREAD

**Issue by sophiamf** [GeertWille/sketch-to-xcode-assets-catalog#18]
I was able to successfully export assets one at a time and all other assets hiding. 

After a few times doing this the artboards froze (something I can't undo). 
<img width="616" alt="screen shot 2015-10-30 at 1 06 51 pm" src="https://cloud.githubusercontent.com/assets/10751578/10852449/1df03414-7f07-11e5-9258-98cf3e0db189.png">

***I'm not sure if it was ever possible to export artboards (appropriately named with the p_u/m/t prefix), this would be nice to have, though, seeing that folders have taken to adding random pixels to the H or W of grouped objects. 

***Would also help (so I don't need to adjust the code) to offer the resolution option Sketch Measure now offers. >>Other screenshot.
<img width="424" alt="screen shot 2015-10-30 at 1 06 18 pm" src="https://cloud.githubusercontent.com/assets/10751578/10852458/2c044fea-7f07-11e5-9825-a34aeab7cb45.png">

**Comment by GeertWille** [comment]
There seems to be a lot of issues regarding the new sketch version and we (developers) didn't got notified about any breaking changes... Right now Bohemian is trying to work out why a lot of the existing plugins don't work anymore. This Friday I'll look into the problem and hope that Bohemian by that time came with a clear guide of what breaking changes they made so I can fix the issues.

Thanks for understanding :)

Also I'll look into your option menu idea... Maybe I'll make it so you can configure the menu items yourself and choose whatever base density you want.

Exporting artboards was never part of the plugin so I can't guarantee that this works. Although if sometimes it looks like sketch is hanging it can also be that it's still doing it's job but because of the fact that we can't run plugins in different threads it basically looks like it's crashing. This all depends on how many assets your are slicing, here at the office we sometimes have to slice more than 200 images and this can take up to 2-4 minutes depending on the specs of your computer.

Here we also had a problem with groups adding random pixels to W or H although it always turned out that designers had forgotten that they had a shadow around an object or other settings that caused this. If you want to slice an exact size you can also use the slicelayer option (see README)... No more problems with added pixels...

**Comment by sophiamf** [comment]
Thanks so much for the details! 

So what I'm seeing is that with the plugin my devs adjusted to scale for 2x works but only one at a time, hiding all other layers.

The hiding/failed batch export on this updated plugin ignore the slice layers. I have the slice and asset in a group named according to your convention. 

Wondering if its somehow turning on "trim transparent pixels"

**Comment by sophiamf** [comment]
Slice layers ignored in 3.4

**Comment by sophiamf** [comment]
Its stopped working all together on sketch 3.4.1 with el capitan. "no layer selected"

**Comment by GeertWille** [comment]
I added "trim transparant pixels" but you can override it if you add a SliceLayer in the group of your asset...

**Comment by GeertWille** [comment]
I fixed the trim transparant pixels... There was indeed a mistake in my code sorry for that but it's fixed now :+1:
